In [1]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

In [2]:
n_samples, n_features = X.shape
print("This datast hsa {0} samples and {1} features". format(n_samples, n_features))
print(X[:5])

This datast hsa 100 samples and 5 features
[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]


In [3]:
features = ["bread", "milk", "cheese", "apples", "bananas"]

In [4]:
num_apple_purchases = 0
for sample in X:
    if smaple[3] == 1;
        num_apple_purchases += 1

print("{0} people bought Apples".format(num_apple_purchases))

SyntaxError: invalid syntax (<ipython-input-4-aad5b181041a>, line 3)